grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  service:
    type: NodePort
    nodePort: 32000
  sidecar:
    dashboards:
      enabled: true
      SCProvider: false
      label: grafana_dashboard
      labelValue: "1"
      folder: /tmp/dashboards
      folderAnnotation: grafana_folder
      searchNamespace: ALL
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: flashcards-shared
          orgId: 1
          folder: FlashCards
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /tmp/dashboards/flashcards/shared
        - name: flashcards-frontend
          orgId: 1
          folder: FlashCards Frontend
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /tmp/dashboards/flashcards/frontend
        - name: flashcards-backend
          orgId: 1
          folder: FlashCards Backend
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /tmp/dashboards/flashcards/backend
        - name: flashcards-hosted
          orgId: 1
          folder: FlashCards Hosted
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /tmp/dashboards/flashcards/hosted
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      editable: true

prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}
    serviceMonitorNamespaceSelector: {}
    scrapeInterval: 30s

alertmanager:
  enabled: false
