apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: backend
  labels:
    app.kubernetes.io/part-of: flashcards
spec:
  namespaceSelector:
    matchNames:
      - moomento
  selector:
    matchLabels:
      app: backend
  podMetricsEndpoints:
    - path: /actuator/prometheus
      targetPort: 8080
      interval: 30s
      scrapeTimeout: 10s
