apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashcards-hosted
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flashcards-hosted
  template:
    metadata:
      labels:
        app: flashcards-hosted
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "flashcards-role"
        vault.hashicorp.com/agent-inject-secret-app.env: "flashcards/backend"
        vault.hashicorp.com/agent-inject-template-app.env: |
          {{- with secret "flashcards/backend" -}}
          JWT_SECRET={{ '{{' }} .Data.data.JWT_SECRET {{ '}}' }}
          SPRING_DATASOURCE_URL={{ '{{' }} .Data.data.SPRING_DATASOURCE_URL {{ '}}' }}
          SPRING_DATASOURCE_USERNAME={{ '{{' }} .Data.data.SPRING_DATASOURCE_USERNAME {{ '}}' }}
          SPRING_DATASOURCE_PASSWORD={{ '{{' }} .Data.data.SPRING_DATASOURCE_PASSWORD {{ '}}' }}
          {{- end -}}
    spec:
      containers:
      - name: app
        image: ghcr.io/path-of-execution-team/flashcardshosted:dev
        imagePullPolicy: IfNotPresent
        ports: 
          - name: http
            containerPort: 8081
        env:
          - name: SPRING_CONFIG_IMPORT
            value: "optional:file:/vault/secrets/app.env"
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "800m"
            memory: "768Mi"
        readinessProbe: 
          httpGet: 
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe: 
          httpGet: 
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: flashcards-hosted
  namespace: dev
spec:
  selector:
    app: flashcards-hosted
  ports:
    - name: http
      port: 8081
      targetPort: 8081