apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashcards-frontend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels: {{ app: flashcards-frontend }}
  template:
    metadata:
      labels: {{ app: flashcards-frontend }}
    spec:
      containers:
      - name: app
        image: ghcr.io/path-of-execution-team/flashcardsgui:prod
        imagePullPolicy: IfNotPresent
        ports: [ {{name: http, containerPort: 3000}} ]
        env:
          - name: NEXT_PUBLIC_API_BASE_URL
            value: "http://flashcards-backend.prod.svc.cluster.local:8080"
        resources:
          requests: {{ cpu: "100m", memory: "128Mi" }}
          limits:   {{ cpu: "500m", memory: "512Mi" }}
---
apiVersion: v1
kind: Service
metadata:
  name: flashcards-frontend
  namespace: prod
spec:
  type: NodePort
  selector: {{ app: flashcards-frontend }}
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30090