global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "backend"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["backend:8080"]

  - job_name: "hosted"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["hosted:8081"]
